version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build: ## New pre-build phase for authentication to ECR with Docker CLI
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - ./mvnw install
      - JAR_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
      ## Now building the Docker image with the docker CLI
      - echo Building the Docker image...
      - docker build --build-arg JAR_FILE=spring-petclinic-$JAR_VERSION.jar -t petclinic:$JAR_VERSION .
      ## And tagging it with correct URI
      - docker tag petclinic:$JAR_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/petclinic:$JAR_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/petclinic:$JAR_VERSION
